CREATE TABLE [dbo].[Users]
(
	[Id]			INT				IDENTITY(1,1)	NOT NULL,
	[Login]			NVARCHAR(50)	UNIQUE			NOT NULL,
	[Password]		NVARCHAR(255)					NOT NULL,
	[IsAdmin]		BIT								NOT NULL,
	CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC)
)
